name: Test dictionaries

on:
  push:
    branches:
    - "**"
    tags-ignore:
    - "**"
  pull_request_target:
    branches:
    - "**"
    types:
    - 'opened'
    - 'reopened'
    - 'synchronize'

jobs:
  dictionaries:
    name: Flaky Dictionaries
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v6
      env:
        GIT_CURL_VERBOSE: True
        GIT_TRACE: True
        GIT_SSH_COMMAND: ssh -v -v -v
    - name: shim dictionary service
      run: |
        cp t/with-dictionaries/unknown-words-server wrappers/unknown-words
    - name: check-spelling
      id: spelling
      uses: ./
      with:
        checkout: false
        post_comment: 0
        config: t/with-dictionaries/config
        dictionary_url: http://localhost:8123/basic.txt
        check_extra_dictionaries:
        extra_dictionaries:
          http://localhost:8123/429.php
          http://localhost:8123/503.php
          http://localhost:8123/sample.txt
